# Generated by Django 4.2.5 on 2023-10-16 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('long_form', models.CharField(max_length=10)),
                ('short_form', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('long_form', models.CharField(max_length=10)),
                ('short_form', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blackjack.cardvalue')),
                ('suit_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blackjack.suit')),
            ],
        ),
    ]
