# Generated by Django 4.2.5 on 2023-10-16 17:21

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='suit_id',
            new_name='suit',
        ),
    ]
