# Generated by Django 4.2.5 on 2023-10-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0003_insert_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('chip_balance', models.IntegerField()),
                ('cash_balance', models.IntegerField()),
            ],
        ),
    ]
