# Generated by Django 4.2.5 on 2023-10-20 14:00

from django.db import migrations, models

from blackjack.models import CardValue

def modify_card_values(apps, schema_editor):
    value = 0
    for card_value in CardValue.objects.all():
        match card_value.short_form:
            case "A":
                value = 1
            case "J":
                value = 11
            case "Q":
                value = 12
            case "K":
                value = 13
            case _:
                value = int(card_value.short_form)
        
        card_value.value = value
        card_value.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0004_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardvalue',
            name='value',
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(modify_card_values),
    ]
