# Generated by Django 4.2.5 on 2023-10-20 14:00

from django.db import migrations, models

from blackjack.models import CardValue

def modify_card_values(apps, schema_editor):
    value = 0
    card_value = CardValue.objects.get(short_form="10")
    card_value.short_form = "T"
    card_value.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0005_cardvalue_value'),
    ]

    operations = [
        migrations.RunPython(modify_card_values),
    ]
